/**
 * UI copy. Spanish, like every other Diagnóstica frontend. Centralized so a
 * future i18next setup only has to move these keys, not hunt through JSX.
 */
const plural = (count: number, singular: string, pluralForm: string) => `${count} ${count === 1 ? singular : pluralForm}`

export const STRINGS = {
  app: {
    name: 'Diagnóstica Admin',
    tagline: 'Administración global',
  },
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Ingresá con tu cuenta de administrador global.',
    statement: 'Un solo panel para marcas, kioscos y configuración compartida.',
    features: {
      brands: 'Marcas y su arquitectura',
      kiosks: 'Cabinas y multis de cada marca',
      schedules: 'Agendas y sus vínculos',
    },
    email: 'Email',
    emailPlaceholder: 'admin@diagnostica.com.ar',
    password: 'Contraseña',
    passwordPlaceholder: 'Ingresá tu contraseña',
    showPassword: 'Mostrar contraseña',
    hidePassword: 'Ocultar contraseña',
    submit: 'Ingresar',
    submitting: 'Ingresando…',
    required: 'Completá el email y la contraseña.',
    errorTitle: 'No pudimos iniciar sesión',
  },
  errors: {
    INVALID_CREDENTIALS: 'Email o contraseña inválidos.',
    ADMIN_DISABLED: 'Tu cuenta de administrador está deshabilitada. Contactá a otro administrador.',
    NETWORK: 'No pudimos conectarnos con el servidor. Revisá tu conexión e intentá de nuevo.',
    UNKNOWN: 'Ocurrió un error inesperado. Intentá de nuevo en unos minutos.',
  },
  shell: {
    account: 'Cuenta',
    logout: 'Cerrar sesión',
    environment: 'Entorno',
    checkingSession: 'Verificando sesión…',
    navigation: 'Principal',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
  },
  theme: {
    label: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
  },
  brands: {
    navLabel: 'Marcas',
    title: 'Marcas',
    subtitle: 'Cabinas, multis y agendas de cada marca, con los vínculos que existen entre ellas.',
    selectBrand: 'Marca',
    selectPlaceholder: 'Seleccioná una marca',
    inactive: 'Inactiva',
    tenantUnavailable: 'Sin base de datos',
    includeDeleted: 'Incluir eliminados',
    refresh: 'Actualizar',
    loadingBrands: 'Cargando marcas…',
    loadingArchitecture: 'Cargando arquitectura…',
    noBrands: 'No hay marcas en la base principal.',
    brandsErrorTitle: 'No pudimos cargar las marcas',
    errorTitle: 'No pudimos cargar la marca',
    retry: 'Reintentar',
    emptyTitle: 'Sin recursos',
    emptyDescription: 'Esta marca no tiene cabinas, multis ni agendas para mostrar.',
    canvasLabel: 'Arquitectura de la marca',
    generatedAt: (when: string) => `Generado ${when}`,
    summary: {
      kiosks: (n: number) => plural(n, 'cabina', 'cabinas'),
      multis: (n: number) => plural(n, 'multi', 'multis'),
      schedules: (n: number) => plural(n, 'agenda', 'agendas'),
      edges: (n: number) => plural(n, 'vínculo', 'vínculos'),
    },
    kinds: {
      kiosk: 'Cabina',
      multi: 'Multi',
      schedule: 'Agenda',
      institution: 'Institución',
    },
    kiosk: {
      connected: 'Conectada',
      disconnected: 'Desconectada',
      lastConnected: (when: string) => `Última conexión ${when}`,
      neverConnected: 'Nunca se conectó',
      exams: (n: number) => plural(n, 'examen configurado', 'exámenes configurados'),
      noExams: 'Sin exámenes configurados',
      accounts: (n: number) => plural(n, 'cuenta asociada', 'cuentas asociadas'),
      noAccounts: 'Sin cuentas asociadas',
      stationAccount: 'Cuenta de estación',
      deleted: 'Eliminada',
      keyboardMode: 'Modo teclado',
      assistantMode: 'Asistente',
      actions: 'Acciones',
      edit: 'Editar',
      editSections: {
        data: 'Datos del dispositivo',
        version: 'Versiones de software',
        devices: 'Dispositivos',
        availableExams: 'Exámenes disponibles',
        params: 'Parámetros',
      } as Record<string, string>,
      duplicate: 'Duplicar en otra marca',
      move: 'Mover a otra marca',
      status: {
        AVAILABLE: 'Disponible',
        PENDING: 'Pendiente',
        BUSY: 'Ocupada',
        IN_USE: 'En uso',
        IN_USE_BY_KIOSK_USER: 'En uso por cuenta de estación',
        MAINTENANCE: 'En mantenimiento',
        DISABLED: 'Deshabilitada',
      } as Record<string, string>,
    },
    schedule: {
      urgency: 'Urgencias',
      users: (n: number) => plural(n, 'usuario con acceso', 'usuarios con acceso'),
      noUsers: 'Sin usuarios con acceso',
      availability: 'Disponibilidad semanal',
      deleted: 'Eliminada',
      noInstitution: 'Sin institución',
    },
    institution: {
      schedules: (n: number) => plural(n, 'agenda', 'agendas'),
    },
    search: {
      label: 'Buscar en la marca',
      placeholder: 'Buscar cabinas, multis, agendas o instituciones…',
      clear: 'Limpiar búsqueda',
      results: (found: number, total: number) => `${found} de ${total}`,
      noResults: 'Sin resultados',
      fitResults: 'Encuadrar resultados',
      more: (n: number) => `+${n} más`,
      hint: 'Enter va al primero · Esc limpia',
    },
    legend: {
      title: 'Leyenda',
      edge: 'Cuenta asociada a la cabina con acceso a la agenda',
    },
    edge: {
      accounts: (n: number) => plural(n, 'cuenta', 'cuentas'),
    },
    dialog: {
      duplicateTitle: 'Duplicar en otra marca',
      duplicateDescription:
        'Se crea una copia con la configuración (exámenes, parámetros, dispositivos). No se copian credenciales, calibraciones, cuentas de estación ni agendas.',
      moveTitle: 'Mover a otra marca',
      moveDescription:
        'La cabina tiene que estar desconectada y sin sesión activa. El dispositivo y su cuenta de estación se reprovisionan en la marca destino.',
      targetBrand: 'Marca destino',
      location: 'Nombre / ubicación de la copia',
      submitDuplicate: 'Duplicar',
      submitMove: 'Mover',
      submitting: 'Procesando…',
      cancel: 'Cancelar',
      close: 'Cerrar',
      duplicated: (location: string, brand: string) => `Se creó «${location}» en ${brand}.`,
      omittedTitle: 'Campos no copiados',
      notCopiedTitle: 'Hay que recrear en la marca destino',
      moveNotImplemented:
        'La migración entre marcas todavía no está disponible. Se validaron la marca, la cabina y el destino; el detalle pendiente está documentado en el backend.',
      resultErrorTitle: 'No se pudo completar la operación',
    },
    edit: {
      loading: 'Cargando configuración…',
      loadError: 'No pudimos cargar la configuración de la cabina.',
      save: 'Guardar cambios',
      saving: 'Guardando…',
      saved: 'Cambios guardados.',
      cancel: 'Cancelar',
      close: 'Cerrar',
      saveErrorTitle: 'No se pudieron guardar los cambios',
      validationTitle: 'Revisá el formulario',
      descriptions: {
        data: 'Identidad y estado operativo de la cabina o multi.',
        version: 'Versiones que reporta cada componente. backend, frontend y berry son obligatorias.',
        devices:
          'Hardware configurado. El nombre identifica al dispositivo ante la cabina; el LED y la etiqueta son cableado de cada unidad.',
        availableExams:
          'Exámenes que ofrece la estación y los dispositivos que usa cada uno. Las instrucciones con imágenes se conservan tal cual.',
        params: 'Configuración de ECG, monitor multiparamétrico, control de red y modos. El video de bienvenida no se modifica desde acá.',
      } as Record<string, string>,
      data: {
        location: 'Nombre / ubicación',
        type: 'Tipo',
        status: 'Estado',
        info: 'Información',
        id: 'ID',
        connection: 'Conexión',
        lastConnected: 'Última conexión',
        lastDisconnected: 'Última desconexión',
        zoom: 'Zoom',
        calibrations: (n: number) => plural(n, 'calibración guardada', 'calibraciones guardadas'),
        never: 'Sin registro',
        locationRequired: 'La ubicación es obligatoria.',
      },
      version: {
        required: 'obligatoria',
        add: 'Agregar componente',
        key: 'Componente',
        value: 'Versión',
        remove: 'Quitar componente',
        keyPlaceholder: 'nombre_componente',
        valuePlaceholder: 'dev, staging, 1.2.0…',
        missingRequired: (keys: string) => `Completá las versiones obligatorias: ${keys}.`,
        invalidKey: 'Cada componente necesita un nombre único, sin espacios.',
      },
      devices: {
        add: 'Agregar dispositivo',
        remove: 'Quitar dispositivo',
        empty: 'Esta cabina no tiene dispositivos configurados.',
        catalog: 'Dispositivo',
        custom: 'Personalizado',
        type: 'Tipo',
        subType: 'Subtipo',
        name: 'Nombre (identificador)',
        nameToShow: 'Nombre a mostrar',
        label: 'Etiqueta del equipo',
        labelHint: 'Vacía = el sistema usa el dispositivo que ofrezca el equipo.',
        ledNumber: 'LED',
        enabled: 'Habilitado',
        videoAnalysis: 'Análisis de video con IA',
        analysisContext: 'Contexto para el análisis',
        analysisContextPlaceholder: 'Qué debe observar el modelo en este dispositivo…',
        compatibleWithKioskMode: 'Compatible con modo cabina',
        thirdParty: 'Software de terceros',
        softwareWindow: 'Ventana del software',
        softwareExecutable: 'Ejecutable',
        resultsDir: 'Carpeta de resultados',
        configDir: 'Carpeta de configuración',
        quiz: 'Cuestionario',
        initialPlanId: 'Plan inicial',
        applicationId: 'Aplicación',
        quizName: 'Nombre del cuestionario',
        dependencies: 'Dependencias (separadas por coma)',
        invalid: (index: number) => `El dispositivo ${index} necesita tipo, subtipo, nombre y nombre a mostrar.`,
      },
      exams: {
        add: 'Agregar examen',
        remove: 'Quitar examen',
        empty: 'Esta cabina no tiene exámenes configurados.',
        catalog: 'Examen',
        custom: 'Personalizado',
        type: 'Tipo (código)',
        name: 'Nombre',
        subtype: 'Subtipo',
        subtypeNone: 'Sin subtipo',
        customPrompt: 'Prompt personalizado',
        customPromptHint: 'Instrucciones adicionales para el análisis asistido por IA.',
        devices: 'Dispositivos',
        addDevice: 'Agregar dispositivo…',
        customDevicePlaceholder: 'Otro dispositivo (nombre)',
        removeDevice: (name: string) => `Quitar ${name}`,
        instructions: (n: number) => (n === 0 ? 'Sin instrucciones' : `${plural(n, 'instrucción', 'instrucciones')} — se conservan`),
        invalid: (index: number) => `El examen ${index} necesita tipo, nombre y al menos un dispositivo.`,
      },
      params: {
        ecg: 'ECG',
        filterFrec: 'Filtro de frecuencia',
        filterMuscle: 'Filtro muscular',
        filterBaseline: 'Filtro de línea base',
        active: 'Activo',
        value: 'Valor',
        stillHereStart: 'Inicio «¿seguís ahí?» (s)',
        stillHerePeriod: 'Período «¿seguís ahí?» (s)',
        stillHereCountdownPeriod: 'Cuenta regresiva (s)',
        monitor: 'Monitor multiparamétrico',
        vital: 'Señal',
        min: 'Mín',
        max: 'Máx',
        alarm: 'Alarma',
        on: 'Encendido',
        minSys: 'Sistólica mín',
        maxSys: 'Sistólica máx',
        minDia: 'Diastólica mín',
        maxDia: 'Diastólica máx',
        measureInterval: 'Intervalo de medición (min)',
        showInstructions: 'Mostrar instrucciones',
        alarmInterval: 'Intervalo de alarma (min)',
        network: 'Control de calidad de red',
        networkEnabled: 'Habilitado',
        intervalMs: 'Intervalo (ms)',
        minDownloadKbps: 'Descarga mínima (kbps)',
        minUploadKbps: 'Subida mínima (kbps)',
        maxLatencyMs: 'Latencia máxima (ms)',
        maxPacketLossPercent: 'Pérdida máxima de paquetes (%)',
        modes: 'Modos',
        keyboardMode: 'Modo teclado',
        assistantMode: 'Modo asistente',
        welcomeVideo: (name: string) => `Video de bienvenida configurado: ${name}. Se conserva.`,
        invalidNumbers: 'Todos los valores numéricos deben ser números válidos.',
      },
    },
    errors: {
      BRAND_NOT_FOUND: 'La marca ya no existe.',
      TENANT_UNAVAILABLE: 'La marca no tiene una base de datos accesible desde este servidor.',
      KIOSK_NOT_FOUND: 'La cabina ya no existe en la marca de origen.',
      TARGET_BRAND_NOT_FOUND: 'La marca destino no existe.',
      TARGET_TENANT_UNAVAILABLE: 'La marca destino no tiene una base de datos accesible.',
      KIOSK_BUSY: 'La cabina está conectada o tiene una sesión activa. Desconectala antes de moverla.',
      MOVE_NOT_IMPLEMENTED: 'La migración entre marcas todavía no está implementada.',
    } as Record<string, string>,
  },
} as const
