/**
 * UI copy. Spanish, like every other Diagnóstica frontend. Centralized so a
 * future i18next setup only has to move these keys, not hunt through JSX.
 */
const plural = (count: number, singular: string, pluralForm: string) => `${count} ${count === 1 ? singular : pluralForm}`

export const STRINGS = {
  app: {
    name: 'Diagnóstica Admin',
    tagline: 'Administración global',
  },
  login: {
    title: 'Iniciar sesión',
    subtitle: 'Ingresá con tu cuenta de administrador global.',
    statement: 'Un solo panel para marcas, kioscos y configuración compartida.',
    features: {
      brands: 'Marcas y su arquitectura',
      kiosks: 'Cabinas y multis de cada marca',
      schedules: 'Agendas y sus vínculos',
    },
    email: 'Email',
    emailPlaceholder: 'admin@diagnostica.com.ar',
    password: 'Contraseña',
    passwordPlaceholder: 'Ingresá tu contraseña',
    showPassword: 'Mostrar contraseña',
    hidePassword: 'Ocultar contraseña',
    submit: 'Ingresar',
    submitting: 'Ingresando…',
    required: 'Completá el email y la contraseña.',
    errorTitle: 'No pudimos iniciar sesión',
  },
  errors: {
    INVALID_CREDENTIALS: 'Email o contraseña inválidos.',
    ADMIN_DISABLED: 'Tu cuenta de administrador está deshabilitada. Contactá a otro administrador.',
    NETWORK: 'No pudimos conectarnos con el servidor. Revisá tu conexión e intentá de nuevo.',
    UNKNOWN: 'Ocurrió un error inesperado. Intentá de nuevo en unos minutos.',
  },
  shell: {
    account: 'Cuenta',
    logout: 'Cerrar sesión',
    environment: 'Entorno',
    checkingSession: 'Verificando sesión…',
    navigation: 'Principal',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    collapseSidebar: 'Contraer menú',
    expandSidebar: 'Expandir menú',
    collapse: 'Contraer',
  },
  theme: {
    label: 'Tema',
    light: 'Claro',
    dark: 'Oscuro',
    system: 'Sistema',
  },
  brands: {
    navLabel: 'Marcas',
    title: 'Marcas',
    subtitle: 'Cabinas, multis y agendas de cada marca, con los vínculos que existen entre ellas.',
    selectBrand: 'Marca',
    selectPlaceholder: 'Seleccioná una marca',
    inactive: 'Inactiva',
    tenantUnavailable: 'Sin base de datos',
    includeDeleted: 'Incluir eliminados',
    refresh: 'Actualizar',
    loadingBrands: 'Cargando marcas…',
    loadingArchitecture: 'Cargando arquitectura…',
    noBrands: 'No hay marcas en la base principal.',
    brandsErrorTitle: 'No pudimos cargar las marcas',
    errorTitle: 'No pudimos cargar la marca',
    retry: 'Reintentar',
    emptyTitle: 'Sin recursos',
    emptyDescription: 'Esta marca no tiene cabinas, multis ni agendas para mostrar.',
    canvasLabel: 'Arquitectura de la marca',
    generatedAt: (when: string) => `Generado ${when}`,
    summary: {
      kiosks: (n: number) => plural(n, 'cabina', 'cabinas'),
      multis: (n: number) => plural(n, 'multi', 'multis'),
      schedules: (n: number) => plural(n, 'agenda', 'agendas'),
      edges: (n: number) => plural(n, 'vínculo', 'vínculos'),
    },
    kinds: {
      kiosk: 'Cabina',
      multi: 'Multi',
      schedule: 'Agenda',
      institution: 'Institución',
    },
    kiosk: {
      connected: 'Conectada',
      disconnected: 'Desconectada',
      lastConnected: (when: string) => `Última conexión ${when}`,
      neverConnected: 'Nunca se conectó',
      exams: (n: number) => plural(n, 'examen configurado', 'exámenes configurados'),
      noExams: 'Sin exámenes configurados',
      accounts: (n: number) => plural(n, 'cuenta asociada', 'cuentas asociadas'),
      noAccounts: 'Sin cuentas asociadas',
      stationAccount: 'Cuenta de estación',
      deleted: 'Eliminada',
      keyboardMode: 'Modo teclado',
      assistantMode: 'Asistente',
      actions: 'Acciones',
      edit: 'Editar',
      editSections: {
        data: 'Datos del dispositivo',
        version: 'Versiones de software',
        devices: 'Dispositivos',
        availableExams: 'Exámenes disponibles',
        params: 'Parámetros',
      } as Record<string, string>,
      duplicate: 'Duplicar en otra marca',
      move: 'Mover a otra marca',
      session: {
        patient: 'Paciente en consulta',
        anonymousPatient: 'Paciente sin identificar',
        patientSince: (since: string) => `En consulta desde ${since}`,
        document: (type: string, value: string) => `${type.toUpperCase()} ${value}`,
        videoVisit: {
          PENDING: 'Esperando profesional',
          WAITING: 'Esperando profesional',
          ACCEPTED: 'En videoconsulta',
        } as Record<string, string>,
        videoVisitFallback: 'Videoconsulta en curso',
        withProfessional: (name: string) => `con ${name}`,
      },
      status: {
        AVAILABLE: 'Disponible',
        PENDING: 'Pendiente',
        BUSY: 'Ocupada',
        IN_USE: 'En uso',
        IN_USE_BY_KIOSK_USER: 'En uso por cuenta de estación',
        MAINTENANCE: 'En mantenimiento',
        DISABLED: 'Deshabilitada',
      } as Record<string, string>,
    },
    schedule: {
      actions: 'Acciones',
      urgency: 'Urgencias',
      users: (n: number) => plural(n, 'usuario con acceso', 'usuarios con acceso'),
      noUsers: 'Sin usuarios con acceso',
      availability: 'Disponibilidad semanal',
      deleted: 'Eliminada',
      noInstitution: 'Sin institución',
    },
    institution: {
      schedules: (n: number) => plural(n, 'agenda', 'agendas'),
    },
    search: {
      label: 'Buscar en la marca',
      placeholder: 'Buscar cabinas, multis, agendas o instituciones…',
      clear: 'Limpiar búsqueda',
      results: (found: number, total: number) => `${found} de ${total}`,
      noResults: 'Sin resultados',
      fitResults: 'Encuadrar resultados',
      more: (n: number) => `+${n} más`,
      hint: 'Enter va al primero · Esc limpia',
    },
    legend: {
      title: 'Leyenda',
      edge: 'Cuenta asociada a la cabina con acceso a la agenda',
    },
    edge: {
      accounts: (n: number) => plural(n, 'cuenta', 'cuentas'),
    },
    dialog: {
      duplicateTitle: 'Duplicar en otra marca',
      duplicateDescription:
        'Se crea una copia con la configuración (exámenes, parámetros, dispositivos). No se copian credenciales, calibraciones, cuentas de estación ni agendas.',
      moveTitle: 'Mover a otra marca',
      moveDescription:
        'La cabina tiene que estar desconectada y sin sesión activa. El dispositivo y su cuenta de estación se reprovisionan en la marca destino.',
      targetBrand: 'Marca destino',
      location: 'Nombre / ubicación de la copia',
      submitDuplicate: 'Duplicar',
      submitMove: 'Mover',
      submitting: 'Procesando…',
      cancel: 'Cancelar',
      close: 'Cerrar',
      duplicated: (location: string, brand: string) => `Se creó «${location}» en ${brand}.`,
      omittedTitle: 'Campos no copiados',
      notCopiedTitle: 'Hay que recrear en la marca destino',
      moveNotImplemented:
        'La migración entre marcas todavía no está disponible. Se validaron la marca, la cabina y el destino; el detalle pendiente está documentado en el backend.',
      resultErrorTitle: 'No se pudo completar la operación',
    },
    delete: {
      menu: 'Eliminar',
      title: (kind: string) => `Eliminar ${kind.toLocaleLowerCase('es')}`,
      description:
        'Es una eliminación lógica: el registro y su historial se conservan y podés volver a verlo con «Incluir eliminados». Deja de aparecer en el panel de la marca.',
      impactTitle: 'Qué deja de estar disponible',
      confirmLabel: (name: string) => `Escribí «${name}» para confirmar`,
      confirmPlaceholder: 'Nombre exacto',
      confirmMismatch: 'Todavía no coincide con el nombre del elemento.',
      submit: 'Eliminar definitivamente del panel',
      submitting: 'Eliminando…',
      cancel: 'Cancelar',
      errorTitle: 'No se pudo eliminar',
      kioskBlocked: 'Esta cabina está en uso. Solo se puede eliminar cuando está desconectada y sin sesión activa.',
      impact: {
        exams: (n: number) => plural(n, 'examen configurado', 'exámenes configurados'),
        accounts: (n: number) => plural(n, 'cuenta de estación asociada', 'cuentas de estación asociadas'),
        scheduleUsers: (n: number) => plural(n, 'usuario con acceso a la agenda', 'usuarios con acceso a la agenda'),
        activeSession: 'Hay una sesión en curso en esta cabina',
        availability: 'Tiene disponibilidad semanal cargada',
        urgency: 'Es la agenda por defecto de urgencias',
      },
    },
    edit: {
      loading: 'Cargando configuración…',
      loadError: 'No pudimos cargar la configuración de la cabina.',
      save: 'Guardar cambios',
      saving: 'Guardando…',
      saved: 'Cambios guardados.',
      cancel: 'Cancelar',
      close: 'Cerrar',
      saveErrorTitle: 'No se pudieron guardar los cambios',
      validationTitle: 'Revisá el formulario',
      descriptions: {
        data: 'Identidad y estado operativo de la cabina o multi.',
        version: 'Versiones que reporta cada componente. backend, frontend y berry son obligatorias.',
        devices:
          'Hardware configurado. El nombre identifica al dispositivo ante la cabina; el LED y la etiqueta son cableado de cada unidad.',
        availableExams:
          'Exámenes que ofrece la estación y los dispositivos que usa cada uno. Las instrucciones con imágenes se conservan tal cual.',
        params: 'Configuración de ECG, monitor multiparamétrico, control de red y modos. El video de bienvenida no se modifica desde acá.',
      } as Record<string, string>,
      data: {
        location: 'Nombre / ubicación',
        type: 'Tipo',
        status: 'Estado',
        info: 'Información',
        id: 'ID',
        connection: 'Conexión',
        lastConnected: 'Última conexión',
        lastDisconnected: 'Última desconexión',
        zoom: 'Zoom',
        calibrations: (n: number) => plural(n, 'calibración guardada', 'calibraciones guardadas'),
        never: 'Sin registro',
        locationRequired: 'La ubicación es obligatoria.',
      },
      version: {
        required: 'obligatoria',
        add: 'Agregar componente',
        key: 'Componente',
        value: 'Versión',
        remove: 'Quitar componente',
        keyPlaceholder: 'nombre_componente',
        valuePlaceholder: 'dev, staging, 1.2.0…',
        missingRequired: (keys: string) => `Completá las versiones obligatorias: ${keys}.`,
        invalidKey: 'Cada componente necesita un nombre único, sin espacios.',
      },
      devices: {
        add: 'Agregar dispositivo',
        remove: 'Quitar dispositivo',
        empty: 'Esta cabina no tiene dispositivos configurados.',
        catalog: 'Dispositivo',
        custom: 'Personalizado',
        type: 'Tipo',
        subType: 'Subtipo',
        name: 'Nombre (identificador)',
        nameToShow: 'Nombre a mostrar',
        label: 'Etiqueta del equipo',
        labelHint: 'Vacía = el sistema usa el dispositivo que ofrezca el equipo.',
        ledNumber: 'LED',
        enabled: 'Habilitado',
        videoAnalysis: 'Análisis de video con IA',
        analysisContext: 'Contexto para el análisis',
        analysisContextPlaceholder: 'Qué debe observar el modelo en este dispositivo…',
        compatibleWithKioskMode: 'Compatible con modo cabina',
        thirdParty: 'Software de terceros',
        softwareWindow: 'Ventana del software',
        softwareExecutable: 'Ejecutable',
        resultsDir: 'Carpeta de resultados',
        configDir: 'Carpeta de configuración',
        quiz: 'Cuestionario',
        initialPlanId: 'Plan inicial',
        applicationId: 'Aplicación',
        quizName: 'Nombre del cuestionario',
        dependencies: 'Dependencias (separadas por coma)',
        invalid: (index: number) => `El dispositivo ${index} necesita tipo, subtipo, nombre y nombre a mostrar.`,
      },
      exams: {
        add: 'Agregar examen',
        remove: 'Quitar examen',
        empty: 'Esta cabina no tiene exámenes configurados.',
        catalog: 'Examen',
        custom: 'Personalizado',
        type: 'Tipo (código)',
        name: 'Nombre',
        subtype: 'Subtipo',
        subtypeNone: 'Sin subtipo',
        customPrompt: 'Prompt personalizado',
        customPromptHint: 'Instrucciones adicionales para el análisis asistido por IA.',
        devices: 'Dispositivos',
        addDevice: 'Agregar dispositivo…',
        customDevicePlaceholder: 'Otro dispositivo (nombre)',
        removeDevice: (name: string) => `Quitar ${name}`,
        instructions: (n: number) => (n === 0 ? 'Sin instrucciones' : `${plural(n, 'instrucción', 'instrucciones')} — se conservan`),
        invalid: (index: number) => `El examen ${index} necesita tipo, nombre y al menos un dispositivo.`,
      },
      params: {
        ecg: 'ECG',
        ecgHint: 'Filtros de la señal y tiempos del aviso de inactividad.',
        filtersGroup: 'Filtros de señal',
        stillHereGroup: 'Aviso «¿seguís ahí?»',
        filterFrec: 'Filtro de frecuencia',
        filterMuscle: 'Filtro muscular',
        filterBaseline: 'Filtro de línea base',
        active: 'Activo',
        value: 'Valor',
        stillHereStart: 'Inicio «¿seguís ahí?» (s)',
        stillHerePeriod: 'Período «¿seguís ahí?» (s)',
        stillHereCountdownPeriod: 'Cuenta regresiva (s)',
        monitor: 'Monitor multiparamétrico',
        monitorHint: 'Rango, alarma y encendido de cada señal que mide el monitor.',
        vitalsGroup: 'Umbrales por señal',
        nibpGroup: 'NIBP · presión no invasiva',
        monitorExtrasGroup: 'Instrucciones y alarmas',
        vital: 'Señal',
        min: 'Mín',
        max: 'Máx',
        alarm: 'Alarma',
        on: 'Encendido',
        minSys: 'Sistólica mín',
        maxSys: 'Sistólica máx',
        minDia: 'Diastólica mín',
        maxDia: 'Diastólica máx',
        measureInterval: 'Intervalo (min)',
        showInstructions: 'Mostrar instrucciones',
        alarmInterval: 'Intervalo de alarma (min)',
        network: 'Control de calidad de red',
        networkHint: 'La cabina mide su conexión cada tanto y avisa cuando no alcanza estos mínimos.',
        networkThresholdsGroup: 'Umbrales',
        networkEnabled: 'Habilitado',
        intervalMs: 'Intervalo (ms)',
        minDownloadKbps: 'Descarga mínima (kbps)',
        minUploadKbps: 'Subida mínima (kbps)',
        maxLatencyMs: 'Latencia máxima (ms)',
        maxPacketLossPercent: 'Pérdida máxima de paquetes (%)',
        modes: 'Modos',
        modesHint: 'Cómo opera la estación. El cambio se aplica cuando la cabina vuelve a leer su configuración.',
        keyboardMode: 'Modo teclado',
        assistantMode: 'Modo asistente',
        welcomeVideo: (name: string) => `Video de bienvenida configurado: ${name}. Se conserva.`,
        invalidNumbers: 'Todos los valores numéricos deben ser números válidos.',
      },
    },
    errors: {
      BRAND_NOT_FOUND: 'La marca ya no existe.',
      TENANT_UNAVAILABLE: 'La marca no tiene una base de datos accesible desde este servidor.',
      KIOSK_NOT_FOUND: 'La cabina ya no existe en la marca de origen.',
      TARGET_BRAND_NOT_FOUND: 'La marca destino no existe.',
      TARGET_TENANT_UNAVAILABLE: 'La marca destino no tiene una base de datos accesible.',
      KIOSK_BUSY: 'La cabina está conectada o tiene una sesión activa. Desconectala antes de moverla.',
      MOVE_NOT_IMPLEMENTED: 'La migración entre marcas todavía no está implementada.',
      SCHEDULE_NOT_FOUND: 'La agenda ya no existe o ya estaba eliminada.',
      SCHEDULE_HAS_APPOINTMENTS: 'La agenda tiene turnos agendados, en espera o en curso. Cerralos o cancelalos antes de eliminarla.',
      CONFIRMATION_MISMATCH: 'El nombre escrito no coincide con el del elemento. Actualizá el panel y volvé a intentarlo.',
      PARAMS_INVALID_VALUE: 'Alguno de los valores no es válido para guardarlo como parámetro.',
      PARAMS_PATH_CONFLICT: 'Dos cambios apuntan al mismo parámetro o a uno dentro de otro. Recargá y volvé a intentarlo.',
      PARAMS_PATH_BLOCKED: 'No se puede crear un parámetro dentro de un valor que no es un objeto.',
      PARAMS_MASKED_VALUE: 'Hay secretos que quedaron con el valor oculto. Ingresá el valor real antes de guardar.',
      PARAMS_REVISION_MISMATCH: 'Otra persona modificó los parámetros mientras editabas.',
    } as Record<string, string>,
    params: {
      title: 'Parámetros',
      open: 'Parámetros',
      subtitle: (brand: string) =>
        `Configuración de ${brand} tal como está guardada en la base principal. Los cambios se aplican al guardar.`,
      back: 'Volver a la arquitectura',
      loading: 'Cargando parámetros…',
      loadError: 'No pudimos cargar los parámetros de la marca.',
      empty: 'Esta marca no tiene parámetros. Agregá el primero.',
      search: 'Buscar parámetro',
      searchPlaceholder: 'Buscar por nombre o valor…',
      clearSearch: 'Limpiar búsqueda',
      noMatches: 'Ningún parámetro coincide con la búsqueda.',
      expandAll: 'Expandir todo',
      collapseAll: 'Contraer todo',
      addRoot: 'Agregar parámetro',
      addChild: 'Agregar dentro',
      addItem: 'Agregar elemento',
      addSubmit: 'Agregar',
      keyLabel: 'Nombre',
      keyPlaceholder: 'nombre_del_parametro',
      kindLabel: 'Tipo',
      rename: 'Renombrar',
      changeKind: 'Cambiar tipo',
      remove: 'Eliminar',
      revert: 'Deshacer cambios',
      confirm: 'Confirmar',
      cancel: 'Cancelar',
      actions: (path: string) => `Acciones de ${path}`,
      toggle: (path: string) => `Expandir o contraer ${path}`,
      kinds: {
        string: 'Texto',
        number: 'Número',
        boolean: 'Booleano',
        null: 'Nulo',
        object: 'Objeto',
        array: 'Lista',
      } as Record<string, string>,
      summary: {
        keys: (n: number) => plural(n, 'clave', 'claves'),
        items: (n: number) => plural(n, 'elemento', 'elementos'),
      },
      change: {
        added: 'Nuevo',
        modified: 'Modificado',
        removed: 'Eliminado',
      },
      secret: 'Secreto',
      secretHint: 'El valor guardado no se muestra. Podés reemplazarlo por uno nuevo.',
      secretReplace: 'Reemplazar',
      secretReplacing: 'Nuevo valor',
      secretCancel: 'Cancelar reemplazo',
      keyErrors: {
        empty: 'El nombre no puede estar vacío.',
        invalid: 'Sin puntos y sin «$» al inicio.',
        duplicate: 'Ya existe un parámetro con ese nombre.',
      },
      pending: (n: number) => plural(n, 'cambio sin guardar', 'cambios sin guardar'),
      pendingTitle: 'Cambios sin guardar',
      showPending: 'Ver cambios',
      hidePending: 'Ocultar cambios',
      undo: (path: string) => `Deshacer ${path}`,
      save: 'Guardar cambios',
      saving: 'Guardando…',
      saved: (n: number) => (n === 0 ? 'No había nada para guardar.' : `Se guardaron ${plural(n, 'cambio', 'cambios')}.`),
      discard: 'Descartar',
      discardTitle: 'Descartar los cambios',
      discardDescription: (n: number) => `Vas a perder ${plural(n, 'cambio sin guardar', 'cambios sin guardar')}.`,
      discardConfirm: 'Descartar',
      leaveTitle: 'Salir sin guardar',
      leaveDescription: (n: number) => `Tenés ${plural(n, 'cambio sin guardar', 'cambios sin guardar')}. Si salís ahora, se pierden.`,
      leaveConfirm: 'Salir sin guardar',
      saveErrorTitle: 'No se pudieron guardar los cambios',
      validationTitle: 'Revisá los parámetros',
      issues: {
        nan: (paths: string) => `Estos valores numéricos no son válidos: ${paths}.`,
        emptySecret: (paths: string) => `Ingresá un valor para estos secretos o cancelá el reemplazo: ${paths}.`,
        maskedValue: (paths: string) => `Estos secretos se copiaron con el valor oculto; ingresá el valor real: ${paths}.`,
      },
      conflictTitle: 'Los parámetros cambiaron mientras editabas',
      conflictDescription: 'Recargamos la versión actual y volvimos a aplicar tus cambios sobre ella. Revisalos y guardá de nuevo.',
      refresh: 'Recargar',
    },
  },
} as const
